version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=mknAdmin
      - POSTGRES_DB=mknDb
      - POSTGRES_PASSWORD=mamatKunem
      - DB_EXTENSION=uuid-ossp
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6377:6377'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
      
volumes:
  db:
    driver: local
  redis-data:
    driver: local